// Generated by purs version 0.13.8
"use strict";
var Effect_Console = require("../Effect.Console/index.js");
var identity = function (a) {
    return a;
};
var createFallback = function (v) {
    if (v === "minmax") {
        return Effect_Console.log("Options is minmax");
    };
    if (v === "media") {
        return Effect_Console.log("Options is media");
    };
    return Effect_Console.log("This is not accepted");
};
module.exports = {
    identity: identity,
    createFallback: createFallback
};
